### ISSUE TITLE
Delete corrupts the data structure

### ISSUE THREAD

**Issue by xiphias** [MishaConway/binary_search_tree#2]
For this program:
```
gem 'binary_search_tree'
require 'binary_search_tree'
require 'binary_search_tree_hash'

b=BinarySearchTreeHash.new
b[3]=2
b[4]=1
b[1]=5


b.delete 1
b.delete 3
puts "Remaining #{b.size}"
b.each{|k,v|
  p "#{k} - #{v}"
}
```

Output is:
```
Remaining 1
"3 - 2"
"4 - 1"
```

**Comment by MishaConway** [comment]
@xiphias Hmm interesting, thanks for reporting this. I will take a look at this tomorrow and see if I can identify the issue. I'll update here shortly.

**Comment by MishaConway** [comment]
@xiphias  I added spec to reproduce and will debug this later. The delete code is a little complex so may need some time to properly diagnose.

**Comment by xiphias** [comment]
I found a ruby treap implementation which is working. I love treaps as they
are much simpler to implement than balanced trees (although they are
randomized data structures). See https://github.com/nakedmoon/treap

**Comment by MishaConway** [comment]
@xiphias Hopefully the treap is working fine for you. I believe I have fixed the issue you found, but don't want to declare that 100% until I write some more rigorous specs. Once I can say this with near certainty I'll close this issue.

If you want to give it another try, pull the latest from master or if you are grabbing as a gem please install version 2.2. You no longer need to explicitly require any files if you use the gem.

**Comment by xiphias** [comment]
Treap is good enough for me, but thanks very much anyways :)
